AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance in Singapore region


Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02e1797d503e673f4
      KeyName: my-key-pair  # Use the specified EC2 Key Pair
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: subnet-01f5e5fa0047fe99c
          GroupSet:
            - sg-0b9163782bad25d58  # Use the specified security group
      # IamInstanceProfile: MyEC2Role
      Tags:
        - Key: Name
          Value: MyEC2Instance
      # UserData:
      #   Fn::Base64: !Sub |
      #     #!/bin/bash
      #     set -e

      #     # Update the package list
      #     sudo apt-get update

      #     # Install Nginx
      #     sudo apt-get install -y nginx

      #     # Install MySQL 8
      #     sudo apt-get install -y mysql-server

      #     # Secure MySQL installation (set a root password and remove anonymous users)
      #     sudo mysql_secure_installation

      #     # Install PHP 8.1 and necessary extensions
      #     sudo apt-get install -y software-properties-common
      #     sudo add-apt-repository ppa:ondrej/php
      #     sudo apt-get update
      #     sudo apt-get install -y php8.1 php8.1-fpm php8.1-mysql php8.1-curl php8.1-json php8.1-cli php8.1-common php8.1-opcache php8.1-mbstring php8.1-zip php8.1-xml

      #     # Configure PHP-FPM for Nginx
      #     sudo systemctl enable php8.1-fpm
      #     sudo systemctl start php8.1-fpm

      #     # Configure Nginx to use PHP-FPM
      #     sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
      #     sudo tee /etc/nginx/sites-available/default <<EOF
      #     server {
      #         listen 80 default_server;
      #         listen [::]:80 default_server;

      #         root /var/www/html;
      #         index index.php index.html index.htm;

      #         server_name _;

      #         location / {
      #             try_files \$uri \$uri/ =404;
      #         }

      #         location ~ \.php$ {
      #             include snippets/fastcgi-php.conf;
      #             fastcgi_pass unix:/run/php/php8.1-fpm.sock;
      #         }

      #         location ~ /\.ht {
      #             deny all;
      #         }
      #     }
      #     EOF

      #     # Test Nginx configuration
      #     sudo nginx -t

      #     # Reload Nginx to apply changes
      #     sudo systemctl reload nginx

      #     # Create a test PHP file to verify installation
      #     echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php

      #     # Restart Nginx and PHP-FPM
      #     sudo systemctl restart nginx
      #     sudo systemctl restart php8.1-fpm

Outputs:
  InstanceId:
    Description: The ID of the created EC2 instance
    Value: !Ref MyEC2Instance
    Export:
      Name: MyEC2InstanceId
